info:
    name: Create Item
    type: http
    seq: 3

http:
    method: POST
    url: "{{baseUrl}}/api/inventory/items"
    auth: bearer

auth:
    type: bearer
    bearer:
        token: "{{token}}"

body:
    type: json
    json: |
        {
          "name": "Composite resin",
          "description": "A2 shade",
          "quantity": 10,
          "unitPrice": 25000
        }

