info:
    name: Delete Expense
    type: http
    seq: 11

http:
    method: DELETE
    url: "{{baseUrl}}/api/inventory/expenses/{{expenseId}}"
    auth: bearer

auth:
    type: bearer
    bearer:
        token: "{{token}}"

