info:
    name: Update Item
    type: http
    seq: 4

http:
    method: PATCH
    url: "{{baseUrl}}/api/inventory/items/{{inventoryItemId}}"
    auth: bearer

auth:
    type: bearer
    bearer:
        token: "{{token}}"

body:
    type: json
    json: |
        {
          "quantity": 20,
          "description": "Updated description"
        }

